// <auto-generated />
using Eyouth1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eyouth1.Migrations
{
    [DbContext(typeof(CompanyCtx))]
    [Migration("20250228212137_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Eyouth1.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MgrName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MgrName = "Robert King",
                            Name = "Human Resources"
                        },
                        new
                        {
                            Id = 2,
                            MgrName = "Emily Carter",
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 3,
                            MgrName = "Michael Adams",
                            Name = "IT"
                        },
                        new
                        {
                            Id = 4,
                            MgrName = "Sophia Martinez",
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 5,
                            MgrName = "Daniel Thompson",
                            Name = "Sales"
                        });
                });

            modelBuilder.Entity("Eyouth1.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeptId")
                        .HasColumnType("int");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DeptId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St",
                            DeptId = 3,
                            Img = "boy.jpg",
                            Name = "Alice Johnson",
                            Salary = 75432.67m
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Elm St",
                            DeptId = 1,
                            Img = "girl.jpg",
                            Name = "Bob Smith",
                            Salary = 52789.34m
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Oak St",
                            DeptId = 5,
                            Img = "boy.jpg",
                            Name = "Charlie Brown",
                            Salary = 88123.45m
                        },
                        new
                        {
                            Id = 4,
                            Address = "101 Maple Ave",
                            DeptId = 2,
                            Img = "girl.jpg",
                            Name = "David Williams",
                            Salary = 63543.12m
                        },
                        new
                        {
                            Id = 5,
                            Address = "222 Pine St",
                            DeptId = 4,
                            Img = "girl.jpg",
                            Name = "Emma Davis",
                            Salary = 91876.89m
                        },
                        new
                        {
                            Id = 6,
                            Address = "333 Birch Rd",
                            DeptId = 3,
                            Img = "boy.jpg",
                            Name = "Frank Miller",
                            Salary = 47654.23m
                        },
                        new
                        {
                            Id = 7,
                            Address = "444 Cedar Ln",
                            DeptId = 1,
                            Img = "girl.jpg",
                            Name = "Grace Wilson",
                            Salary = 68789.45m
                        },
                        new
                        {
                            Id = 8,
                            Address = "555 Spruce Ct",
                            DeptId = 2,
                            Img = "boy.jpg",
                            Name = "Henry Moore",
                            Salary = 79999.99m
                        },
                        new
                        {
                            Id = 9,
                            Address = "666 Willow Dr",
                            DeptId = 5,
                            Img = "girl.jpg",
                            Name = "Ivy Taylor",
                            Salary = 56432.78m
                        },
                        new
                        {
                            Id = 10,
                            Address = "777 Ash Blvd",
                            DeptId = 4,
                            Img = "girl.jpg",
                            Name = "Jack White",
                            Salary = 84567.90m
                        });
                });

            modelBuilder.Entity("Eyouth1.Models.Employee", b =>
                {
                    b.HasOne("Eyouth1.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Eyouth1.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
